"""Generates `EVENT_CATALOG.md` from `EventRegistry` (EPIC-008B).

Not a hand-maintained document — see
`sagittarius_engine/domain/event_registry.py`'s module docstring for why an
enum-of-events or a hand-written catalog were both rejected in favor of a
registry that events populate themselves at import time.

Usage:
    python scripts/generate_event_catalog.py [output.md]

Default output: `EVENT_CATALOG.md` at the repository root. Every module
under `sagittarius_engine/` is imported first (reusing
`tests/test_all_modules_importable.py`'s walk) so an event registered inside
a rarely-imported module (an extension nobody has instantiated yet) still
appears — `EventRegistry.register()`/`register_named()` both run as a side
effect of importing the module the event is defined in, not of using it.
"""

from __future__ import annotations

import importlib
import pkgutil
import sys
from pathlib import Path

import sagittarius_engine
from sagittarius_engine.domain import EventRegistry

_DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "EVENT_CATALOG.md"

_HEADER = """\
# Event Catalog

Generated by `scripts/generate_event_catalog.py` from `EventRegistry` — do
not hand-edit. A test (`tests/domain/test_event_registry.py`) asserts this
file matches what the registry produces; regenerate it instead of editing it
directly when an event is added, removed, or renamed.

| Event name | Class | Module | Payload fields |
| :--- | :--- | :--- | :--- |
"""


def _import_every_module() -> None:
    """Imports every module under `sagittarius_engine/` so every event class
    has had the chance to register itself — same walk as
    `tests/test_all_modules_importable.py`, which already tolerates the
    handful of modules with a documented reason to be skipped (Qt platform
    plugin requirements, etc.) by simply not being reachable from here in a
    headless run; a module that fails to import for a genuine defect is
    already caught by that test and is not this script's job to catch."""
    for module_info in pkgutil.walk_packages(
        sagittarius_engine.__path__, prefix="sagittarius_engine."
    ):
        try:
            importlib.import_module(module_info.name)
        except Exception:  # noqa: BLE001 — best-effort; import failures are that test's job
            continue


def render_catalog() -> str:
    _import_every_module()
    lines = [_HEADER.rstrip("\n")]
    for entry in EventRegistry.all():
        payload = ", ".join(entry.payload_fields) if entry.payload_fields else "—"
        lines.append(
            f"| `{entry.event_name}` | `{entry.qualname}` | `{entry.module}` | {payload} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    output = Path(argv[0]) if argv else _DEFAULT_OUTPUT
    output.write_text(render_catalog(), encoding="utf-8")
    print(f"Wrote {output} ({len(EventRegistry.all())} events)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
